name: Metrics
on:
  schedule: # Runs at 6am UTC every day
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: "America/Los_Angeles"
          config_output: svg
          plugin_followup: yes
